{
 "title": "数据量分日展板",
 "description": "根据产品包、是否过滤一次未点击及是否存在四种来源，展示曝光量、点击量、去重用户",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "channel",
    "label": "频道",
    "query": "{\"find\": \"terms\", \"field\": \"channel\"} "
   },
   {
    "name": "packid",
    "label": "产品包",
    "query": "{\"find\": \"terms\", \"field\": \"packId\"}"
   },
   {
    "name": "request",
    "label": "过滤一次未点击",
    "query": "{\"find\": \"terms\", \"field\": \"request_active\"}"
   },
   {
    "name": "allsource",
    "label": "包含所有来源",
    "query": "{\"find\": \"terms\", \"field\": \"four_source\"}"
   },
   {
    "name": "mediashape",
    "label": "内容形态",
    "query": "{\"find\": \"terms\", \"field\": \"mediaShape\"} "
   },
   {
    "name": "contdisplayname",
    "label": "一级分类",
    "query": "{\"find\": \"terms\", \"field\": \"contDisplayName\"}"
   },
   { "name": "filter", "label": "自定义筛选" }
  ]
 },
 "panels": [
  {
   "title": "指定筛选条件—不同渠道曝光量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "channel:$channel AND packId:$packid AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "总量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "packId:$packid AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定筛选条件—不同渠道点击量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "channel:$channel AND packId:$packid AND click:1 AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "总量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "packId:$packid AND click:1 AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定筛选条件—不同渠道曝光视频量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "search_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND packId:$packid AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "总量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "packId:$packid AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定筛选条件—不同渠道去重用户量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "channel:$channel AND packId:$packid AND click:1 AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "总量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "packId:$packid AND click:1 AND four_source:$allsource AND  request_active:$request AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定产品包-未注册用户量统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "活跃用户量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND register_user:0 AND request_active:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "请求量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND register_user:0 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定产品包-未注册用户区分来源点击量统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "channel:$channel AND register_user:0 AND click:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "总量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "user_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "channel:$channel AND register_user:0 AND click:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定产品包-注册用户量统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "活跃用户量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND register_user:1 AND request_active:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "请求量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND register_user:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定产品包-注册用户区分来源点击量统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "user_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "channel:$channel AND register_user:1 AND click:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "总量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "user_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "channel:$channel AND register_user:1 AND click:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定产品包-活跃用户请求量统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "用户数",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND request_active:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "请求量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND request_active:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "指定产品包-活跃用户点击量统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "用户数",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "channel:$channel AND request_active:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    },
    {
     "alias": "点击量",
     "bucketAggs": [
      { "field": "timeLocal", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "channel:$channel AND request_active:1 AND click:1 AND packId:$packid AND mediaShape:$mediashape AND contDisplayName:$contdisplayname",
     "timeField": "timeLocal"
    }
   ]
  },
  {
   "title": "零元包分cpid曝光量",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cp_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timeLine", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "exposure",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timeLine"
    }
   ]
  },
  {
   "title": "零元包分cpid点击量",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cp_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timeLine", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_click",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timeLine"
    }
   ]
  }
 ]
}